"""Add onboarding_completed to users

Revision ID: 1375a454a7f0
Revises: 172d2ca5cae9
Create Date: 2026-06-11 11:28:18.709308
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1375a454a7f0'
down_revision: Union[str, None] = '172d2ca5cae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_completed')
    # ### end Alembic commands ###
